version: '3'

includes:
  hugo: ./Taskfile_{{OS}}.yml

tasks:
  default:
    desc: 'Run hugo:serve on {{OS}}'
    cmds:
      - task: 'hugo:serve'

  build:
    desc: 'Build site'
    cmds:
      - hugo --minify
