version: '3'

includes:
  hugo: ./Taskfile_{{OS}}.yml

tasks:
  default:
    desc: 'Run hugo:serve on {{OS}}'
    cmds:
      - task: 'hugo:serve'
        vars:
          HUGO_FLAGS: '-D'

  preview:
    desc: 'Run hugo:serve on {{OS}}, no drafts'
    cmds:
      - task: 'hugo:serve'
        vars:
          HUGO_FLAGS: ''

  build:
    desc: 'Build site'
    cmds:
      - hugo --minify --baseURL https://adamross.dev

  deploy:
    desc: 'Deploy site'
    cmds:
      - task: 'build'
      - 'firebase deploy'

  new-*:
    desc: 'Start a new {{.SECTION | default "post"}}. Run as "task new-<section> -- <content dir>'
    cmds:
      - hugo new {{.SECTION}}/{{.CLI_ARGS}}/index.md
    vars:
      SECTION: '{{index .MATCH 0}}'
